### ISSUE TITLE
Cannot read DB

### ISSUE THREAD

**Issue by ybabel** [Urban82/BeurerScaleManager#2]
I'have managed to look into the database. 
I have 2 record stored.
But when I launch the application, none is loaded. No error messages.

**Comment by Urban82** [comment]
Can you try the following steps?
- Start the application with an empty DB
- Download data from the scale
- When prompted, add the users from the scale
- Close the application
- Look on the DB and check that the users are present in the table UserData
- Start again the application and check that the users are present in the droplist

In my computer they are loaded at each start.

**Comment by ybabel** [comment]
Thank you, but it's note a bug, I was speaking of measurements, not users. I didn't understand at the time of writing the issue that the code was not complete. You can close this issue too !
