### ISSUE TITLE
Only retrieves birthdate + height of the stored persons, but no scale measurements

### ISSUE THREAD

**Issue by thomas725** [Urban82/BeurerScaleManager#4]
Hi there!

I've just stumbled upon this repository, really amazing that this exists, thank you!

Sadly I couldn't get it working completely with my BF-100:
It only retrieves birth-date + height of the stored persons and asks me to enter names for them which are written to `~/.BeurerScaleManager/BeurerScaleManager.db` but no scale measurements are retrieved. Also no errors as to why that might be are shown.

Here's the terminal output:
```
Loading translation for "en_US" 
User directory "/home/user" OK 
User saving directory "/home/user/.BeurerScaleManager" OK 
DB in "/home/user/.BeurerScaleManager/BeurerScaleManager.db" 
libusb initialized 
START download 
USB device opened 
Detaching kernel driver... 
Kernel driver detached 
Claiming interface... 
Interface claimed 
Register for interrupt data 
Send control request 
Released interface 
Closed USB device 
END download 
Data received: 8192 bytes 
Parsed 4 users 
Scale date and time is QDateTime("Di. Mär 12 12:08:00 2024") 
```

Please help me debug this!

**Comment by thomas725** [comment]
Ah! after reading through the two closed issues it seems this functions "as designed" as in retrieving measurements has not been implemented (yet). Sad :(

**Comment by Urban82** [comment]
Hi,

this project was never completed because my Beurer scale stopped working and I didn't add access to the data anymore.

I do not remember exactly what the status was, but if I'm not wrong the data from measurements were downloaded correctly and displayed in the grid, but not saved on the DB then (even if something is ready for it in the code).

**Comment by thomas725** [comment]
Thanks for the explanations!

I've found this Python Script that I was able to use to retrieve the data:
https://github.com/rwrnet/BeurerScaleManagerCLI

And wrote this Rust program to parse it because my Beurer BF100 Scale has a different data layout:
https://gitlab.com/thomas351/beurer_bf100_parser/-/blob/master/src/main.rs

This different binary layout probably also is, what caused me to not see any measurements in your GUI.

Kind Regards,
Thomas
